from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Any, Protocol

from .models import Deadline


class Repository(Protocol):
    """Storage contract shared by SQLite local/tests and PostgreSQL live profile.

    The transaction handle intentionally exposes a small DB-API execute surface:
    the service owns atomic state transitions while adapters own persistence.
    """

    conn: Any
    lock: Any

    def tx(self) -> AbstractContextManager[Any]: ...
    def add_chat(self, chat_id: str, timezone_id: str) -> None: ...
    def set_chat_enabled(self, chat_id: str, enabled: bool) -> None: ...
    def global_sends_enabled(self) -> bool: ...
    def set_global_sends_enabled(self, enabled: bool, *, actor_id: str, reason: str, now: datetime | None = None) -> None: ...
    def runtime_setting_enabled(self, key: str, *, conn: Any | None = None, lock: bool = False) -> bool: ...
    def set_runtime_setting(self, key: str, enabled: bool, *, actor_id: str, reason: str, now: datetime | None = None) -> None: ...
    def global_writes_enabled(self) -> bool: ...
    def global_llm_enabled(self) -> bool: ...
    def chat(self, chat_id: str) -> Any: ...
    def list_deadlines(self, chat_id: str) -> list[Deadline]: ...
    def get_deadline(self, chat_id: str, deadline_id: str) -> Deadline | None: ...
    def find_deadlines(self, chat_id: str, query: str) -> list[Deadline]: ...
    def upsert_participant(self, chat_id: str, user_id: str, display_name: str, username: str | None, now: datetime, *, source: str = "observed", explicit: bool = False) -> None: ...
    def opt_out_participant(self, chat_id: str, user_id: str, now: datetime) -> bool: ...
    def list_participants(self, chat_id: str) -> list[dict]: ...
    def recent_call_all(self, chat_id: str, since: datetime) -> bool: ...
    def ensure_monthly_csat(self, now: datetime) -> int: ...
    def record_csat_response(self, survey_id: str, chat_id: str, user_id: str, score: int, now: datetime) -> str | None: ...
    def csat_statistics(self, period: str | None = None) -> dict: ...
    def create_pending(self, chat_id: str, actor_id: str, action: str, payload: dict, now: datetime) -> str: ...
    def acquire_idempotency_lock(self, conn: Any, key: str) -> None: ...
    def pending_for_update(self, conn: Any, pending_id: str, chat_id: str, actor_id: str, now: datetime) -> Any: ...
    def get_material(self, chat_id: str, material_id: str) -> dict | None: ...
    def find_material_by_canonical_url(self, chat_id: str, canonical_url: str) -> dict | None: ...
    def list_materials(self, chat_id: str) -> list[dict]: ...
    def search_materials(self, chat_id: str, query: str) -> list[dict]: ...
    def claim_due_deliveries(self, now: datetime, limit: int = 20, lease_seconds: int = 60) -> list[dict]: ...
    def mark_delivery_sending(self, job_key: str, now: datetime) -> bool: ...
    def mark_delivery_succeeded(self, job_key: str, telegram_message_id: str, now: datetime) -> bool: ...
    def mark_delivery_failed(self, job_key: str, error: str, now: datetime, retryable: bool = True) -> bool: ...
    def mark_delivery_unknown(self, job_key: str, error: str, now: datetime) -> bool: ...
    def list_unknown_deliveries(self, limit: int = 100) -> list[dict]: ...
    def inspect_delivery(self, job_key: str) -> dict | None: ...
    def resolve_delivery_unknown(self, job_key: str, decision: str, actor_id: str, now: datetime, *, reason: str = "") -> bool: ...
